version: "3.8"

name: lendbor-bot
services:
  app:
    container_name: lendbor-app
    build: .
#    command: gunicorn --bind 0.0.0.0:4200 app:app
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "4200:4200"
    depends_on:
      - db
      - redis

  redis:
    container_name: lendbor-redis
    image: "redis:latest"
    ports:
      - "6379:6379"

  db:
    container_name: lendbor-db
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lendbor_db

  nginx:
    container_name: lendbor-nginx
    image: nginx:1.19.10-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  postgres_data: